language: node_js
node_js:
  - "0.11"
before_install:
  - npm install grunt-cli -g
script:
  - grunt compress-images --sourceFile=working/image/large_1.png --destinationFolder=working/image_comp/
  - grunt watch --sourceFolderPath=working/js/ --desnationFolder=working/js_concat/